jobs:
  - name: j1_branch
    type: runSh
    steps:
      - TASK:
        - script: echo "Hello from j1"
        - script: echo versionName=$(date) > $JOB_DIR/my_state_branch.env
        - script: echo foo="bar" >> $JOB_DIR/my_state_branch.env
      - OUT: my_state_branch
      
  - name: j2_branch
    type: runSh
    steps:
      - TASK:
        - script: echo "Hello from j2"
        - script: echo versionName=$(date) > $JOB_DIR/my_state_branch.env
      - OUT: my_state_branch

  - name: j3_branch
    type: runSh
    steps:
      - IN: my_state_branch
      - TASK:
        - script: echo "Hello from j3"
        - script: cat /build/IN/my_state/version.json

  - name: j4_branch
    type: runSh
    steps:
      - IN: my_state_branch
      - TASK:
        - script: echo "Hello from j4"
        - script: cat /build/IN/my_state/version.json
